# Identificación del proyecto
sonar.projectKey=demo-coverage-richard
sonar.projectName=demo_coverage_richard
sonar.projectVersion=1.0

# URL del servidor SonarQube
sonar.host.url=http://localhost:9000

# Token
sonar.login=sqa_700d2cf599399b198183964792ed6fae8ff1aadc
# sonar.token=sqa_700d2cf599399b198183964792ed6fae8ff1aadc

# Código fuente
sonar.sources=src

# Archivos a excluir
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**

# Coverage report generado
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Para TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8
